default_context:
  project_name: 'trading-history'
  project_slug: 'trading-history'
  domain_main: 'trading-history.com'
  domain_staging: 'stag.trading-history.com'
  docker_swarm_stack_name_main: 'trading-history-com'
  docker_swarm_stack_name_staging: 'stag-trading-history-com'
  secret_key: 'a34ba469c6baf0fcaed473ddc4efe85b96e7b29e0bede3df1b1f4569c1e65c8b'
  first_superuser: 'admin@trading-history.com'
  first_superuser_password: 'jst8sdkkk3alskdjf'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.trading-history.com", "https://stag.trading-history.com", "https://trading-history.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@trading-history.com'
  postgres_password: 'jst8sdkkk3alskdjf'
  pgadmin_default_user: 'admin@trading-history.com'
  pgadmin_default_user_password: 'jst8sdkkk3alskdjf'
  traefik_constraint_tag: 'trading-history.com'
  traefik_constraint_tag_staging: 'stag.trading-history.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:jst8sdkkk3alskdjf'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
